### ISSUE TITLE
update to new

### ISSUE THREAD

**Issue by skidxml** [BrodyHstuff/BrodyHstuff.github.io#2]
up date to the new BrodyH.Net ver sion!!!!!!!!!!!!!! i hate you!!!!!!!!!!!11 go die

**Comment by BrodyHstuff** [comment]
ok cool

**Comment by skidxml** [comment]
NO!!!!!!!!!! UN CLOSE BEFORE I GET YOUR'E IP ADDRESS AND FUCKGI NFAJSN F=KIL  YOU!!!!!!!!!!!!!
